sudo: false
language: node_js
env:
  - APP_DIR=src
node_js:
  - 8
  - 10
  - 12
  - node
script:
  - npm install
  - npm run lint
  - npm test
notifications:
  email:
    on_success: never
    on_failure: always
